source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'rake', '= 0.8.7'

group :development, :test do
  gem "rspec", "= 2.0.0"
  gem "rspec-rails", "= 2.0.0"
  gem 'nokogiri', '= 1.5.10'
  gem "cucumber", "= 0.9.2"
  gem "cucumber-rails", "= 0.3.2"
  gem "webrat", "= 0.7.2"
  gem "database_cleaner", "= 0.5.2"
end